"""posts table

Revision ID: 369b85dfe200
Revises: 719236370615
Create Date: 2023-04-22 23:51:03.435447

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '369b85dfe200'
down_revision = '719236370615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrate_version',
                    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
                    sa.Column('repository_path', sa.TEXT(), nullable=True),
                    sa.Column('version', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('repository_id')
                    )
    # ### end Alembic commands ###
